# Generated by Django 3.1.7 on 2021-03-23 18:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('imageurl', models.CharField(max_length=128)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=1024)),
                ('category', models.CharField(max_length=32)),
                ('close', models.CharField(default='false', max_length=10)),
                ('name', models.ManyToManyField(related_name='user_listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
