# Generated by Django 3.1.7 on 2021-03-24 10:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210324_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='name',
            field=models.ManyToManyField(blank=True, related_name='user_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
